#!/bin/bash
export CROSS_COMPILE=aarch64-linux-gnu-
export ARCH=arm64
echo "use make defconfig to update config to .config"
echo "sudo make_ext4fs -l 1024M  -s -a system image/tmp.img image/system/"
echo "simg2img image/tmp.img image/system.img"
