#!/bin/sh
#
# Start mount cgroup sub point....
#
echo "Start mount cgroup sub point..."
mount -t tmpfs none /sys/fs/cgroup

mkdir /sys/fs/cgroup/cpuset
mount -t cgroup -o cpuset cgroup /sys/fs/cgroup/cpuset

mkdir /sys/fs/cgroup/cpu,cpuacct
mount -t cgroup -o cpu,cpuacct cgroup /sys/fs/cgroup/cpu,cpuacct

mkdir /sys/fs/cgroup/hugetlb
mount -t cgroup -o hugetlb cgroup /sys/fs/cgroup/hugetlb

mkdir /sys/fs/cgroup/devices
mount -t cgroup -o devices cgroup /sys/fs/cgroup/devices

mkdir /sys/fs/cgroup/memory
mount -t cgroup -o memory cgroup /sys/fs/cgroup/memory

mkdir /sys/fs/cgroup/blkio
mount -t cgroup -o blkio cgroup /sys/fs/cgroup/blkio

mkdir /sys/fs/cgroup/net_cls
mount -t cgroup -o net_cls cgroup /sys/fs/cgroup/net_cls

mkdir /sys/fs/cgroup/freezer
mount -t cgroup -o freezer cgroup /sys/fs/cgroup/freezer

mkdir /sys/fs/cgroup/pids
mount -t cgroup -o pids cgroup /sys/fs/cgroup/pids

mkdir /sys/fs/cgroup/rdma
mount -t cgroup -o rdma cgroup /sys/fs/cgroup/rdma

mkdir /sys/fs/cgroup/perf_event
mount -t cgroup -o perf_event cgroup /sys/fs/cgroup/perf_event
